# Generated by Django 5.1 on 2024-10-14 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('some_app_blog_maybe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, default='', unique=True, verbose_name='Слаг'),
        ),
    ]
